
CREATE TABLE IF NOT EXISTS public.lab
(
    lab_id SERIAL PRIMARY KEY,
    encounter_id integer,
    specimen integer,
    sample_blood integer,
    sample_urine integer,
    sample_swab integer,
    sample_aza character varying(45) COLLATE pg_catalog."default",
    ebola_rdt integer,
    ebola_rdt_date character varying(15) COLLATE pg_catalog."default",
    ebola_rdt_results integer,
    ebola_pcr integer,
    ebola_pcr_aza character varying(45) COLLATE pg_catalog."default",
    ebola_pcr_date character varying(15) COLLATE pg_catalog."default",
    ebola_pcr_gp integer,
    ebola_pcr_gp_ct double precision,
    ebola_pcr_np integer,
    ebola_pcr_np_ct double precision,
    ebola_pcr_indeterminate integer,
    malaria_rdt_date character varying(15) COLLATE pg_catalog."default",
    malaria_rdt_result integer,
    blood_culture_date character varying(15) COLLATE pg_catalog."default",
    blood_culture_result integer,
    test_pos_infection integer,
    test_pos_infection_aza character varying(45) COLLATE pg_catalog."default",
    haemoglobinuria integer,
    proteinuria integer,
    hematuria integer,
    blood_gas integer,
    ph double precision,
    pco2 double precision,
    pao2 double precision,
    hco3 double precision,
    oxygen_therapy double precision,
    alt_sgpt double precision,
    ast_sgo double precision,
    creatinine double precision,
    potassium double precision,
    urea double precision,
    creatinine_kinase double precision,
    calcium double precision,
    sodium double precision,
    alt_sgpt_nd integer,
    ast_sgo_nd integer,
    creatinine_nd integer,
    potassium_nd integer,
    urea_nd integer,
    creatinine_kinase_nd integer,
    calcium_nd integer,
    sodium_nd integer,
    glucose double precision,
    lactate double precision,
    haemoglobin double precision,
    total_bilirubin double precision,
    wbc_count double precision,
    platelets double precision,
    pt double precision,
    aptt double precision,
    glucose_nd integer,
    lactate_nd integer,
    haemoglobin_nd integer,
    total_bilirubin_nd integer,
    wbc_count_nd integer,
    platelets_nd integer,
    pt_nd integer,
    aptt_nd integer,
    ebola_rdt_aza character varying(46)
);

CREATE TABLE IF NOT EXISTS public.status
(
    status_id SERIAL PRIMARY KEY,
    client_id integer,
    status_date character varying(20),
    status character varying(15),
    status_notes character varying(65),
    updated_by integer,
    updated_on character varying(25),
);